### ISSUE TITLE
tryToLoadFromExport doesn't work on Windows when the require.cache case evaluates to true

### ISSUE THREAD

**Issue by jbaranski** [ardatan/graphql-toolkit#260]
#231 fixed one issue but now I'm seeing another on Windows.

When `rawFilePath` comes in to `tryToLoadFromExport` it has linux style absolute file path (that's good because `await eval(`require('${filePath}');`);` needs linux style absolute path even on Windows). 

The problem is when the `require.cache` case is hit this code converts the `filePath` back to Windows style absolute file path and the same error noted in #231 happens, only it's suppressed now so the real error gets swallowed and a general error shows up:

```
× src/graphql/generated/index.ts
    Error: Failed to load schema
        at Object.exports.loadSchema (C:\Users\jbaranski\Documents\taskport\taskport\core-server\node_modules\@graphql-codegen\cli\src\load.ts:80:11)
```

**Comment by ardatan** [comment]
Could you try with `0.5.17-ddafc4c.0`?

**Comment by dotansimha** [comment]
@jbaranski ?

**Comment by elincognito** [comment]
Hi @dotansimha @ardatan 

I am running on windows and having issues 
with the imports 

``` Unable to load from file "C:\\Users\\Utilizador\\Desktop\\radum-backend-2\\src\\schema.ts": Cannot find module 'C:UsersUtilizadorDesktop\radum-backend-2srcschema.ts'\n```

Utilizador is my user name on windows, as you can see some path separators are being swallowed

the problem goes away if i replace

``` const rawExports = await eval(`require('${filePath}');`);  ```

with 

``` const rawExports = await eval(`require('${filePath.replace(/\\/g, '\\\\')}');`); ```

I.E proper escape \ path separators 

PS: tried also with `0.5.17-ddafc4c.0`

Please ignore this, if its unrelated with @jbaranski issue.

**Comment by jbaranski** [comment]
@dotansimha @ardatan What `graphql-code-generator` version should I use. That's the tool I'm using and this is a transitive dependency there.

**Comment by jbaranski** [comment]
@elincognito I reported that issue under https://github.com/ardatan/graphql-toolkit/issues/231, and it was addressed with the latest version but I had a lingering issue which I reported here.

**Comment by dotansimha** [comment]
Fixed in v0.5.17

**Comment by jbaranski** [comment]
This still doesn't work. I'm using `@graphql-codegen` tooling at `1.8.2`.

**Comment by ahmedkotb** [comment]
@dotansimha this is still reproing in `graphql-toolkit` 0.6.6 on windows

**Comment by ardatan** [comment]
https://github.com/ardatan/graphql-toolkit/pull/307
Could you try with the following canary version?
 0.6.6-alpha-fb57c4b.8+fb57c4b

**Comment by inginheiiro** [comment]
`
const replace = require('replace-in-file');
const os = require('os');

if (process.platform == "win32" || process.platform == "win64") {
    const options = {
        files: 'node_modules/@graphql-toolkit/code-file-loader/dist/commonjs/load-from-code-file.js',
        from: ['filePath = eval(`require.resolve(\'${filePath}\')`);', 'const rawExports = await eval(`require(\'${filePath}\');`);'],
        to: ['filePath = eval(`require.resolve(\'${filePath.replace(/\\\\/g, \'\\\\\\\\\')}\')`);','const rawExports = await eval(`require(\'${filePath.replace(/\\\\/g, \'\\\\\\\\\')}\');`);']
    };

    try {
        const changedFiles = replace.sync(options);
        if(changedFiles.hasChanged) {
            console.log('Modified files !!', changedFiles.file);
        } else {
            console.log('No changes ');
        }
    }
    catch (error) {
        console.error('Error occurred:', error);
    }
}
`


temporary Fix.

node fix-graphql-codegen.js && graphql-codegen

**Comment by smeijer** [comment]
For those trying to parse the post above me.

```js
const replace = require("replace-in-file");
const os = require("os");

if (process.platform == "win32" || process.platform == "win64") {
  const options = {
    files:
      "node_modules/@graphql-toolkit/code-file-loader/dist/commonjs/load-from-code-file.js",
    from: [
      "filePath = eval(`require.resolve('${filePath}')`);",
      "const rawExports = await eval(`require('${filePath}');`);"
    ],
    to: [
      "filePath = eval(`require.resolve('${filePath.replace(/\\\\/g, '\\\\\\\\')}')`);",
      "const rawExports = await eval(`require('${filePath.replace(/\\\\/g, '\\\\\\\\')}');`);"
    ]
  };

  try {
    const changedFiles = replace.sync(options);
    if (changedFiles.hasChanged) {
      console.log("Modified files !!", changedFiles.file);
    } else {
      console.log("No changes ");
    }
  } catch (error) {
    console.error("Error occurred:", error);
  }
}

```

```
node fix-graphql-codegen.js && graphql-codegen
```

But this fix can be so easy, can it not? Just replace every `\` in `filePath` with `/`. As unix systems don't use `\`, and Windows accepts both. Extra benefith is that `/` doesn't need to be escaped.
