### ISSUE TITLE
Error: "Query" defined in resolvers but not in schema in V0.7.5

### ISSUE THREAD

**Issue by ahrbil** [ardatan/graphql-toolkit#385]
I have a folder with .graphql files and I'm using **loadSchemaFiles** function to load them all and then 
**mergeTypeDefs** to merge all the typedefs.
But I'm getting this error:
`Error: "Query" defined in resolvers but not in schema` also **loadSchemaFiles** returns an empty array.
I have tried all the versions between V0.7.5 and 0.4.2 it seems to works only in 0.4.2.

**Comment by ardatan** [comment]
@ahrbil Could you try with the following version?
`0.7.6-alpha-43bdd2c.10+43bdd2c`

**Comment by ahrbil** [comment]
@ardatan Yes, I'm.
I just realized that. I have tried running the code on WSL Ubuntu and it works just fine.
I'm still having the same issue on windows even with the version: `0.7.6-alpha-43bdd2c.10+43bdd2c`
here is a simple repo :
[https://github.com/ahrbil/apollo-backpack-typescript](https://github.com/ahrbil/apollo-backpack-typescript).
Also, I'm getting the same error on the deployment server. (we are using Zeit now) I tried the alpha version and it is also not working

**Comment by ardatan** [comment]
@ahrbil I pushed another fix to respect Windows paths;
`0.7.6-alpha-1852071.8+1852071`
Could you try with this again?

**Comment by ahrbil** [comment]
@ardatan I couldn't find this version

**Comment by ardatan** [comment]
@ahrbil 
Something looks wrong in NPM. I released another alpha version. You can try with `0.7.6-alpha-5f84046.29+5f84046`

**Comment by ahrbil** [comment]
@ardatan I'm sorry but I still can't get this version installed.

![image](https://user-images.githubusercontent.com/16563523/71616023-68c3ee00-2bb4-11ea-8d7e-73231a818482.png)

**Comment by ardatan** [comment]
@ahrbil We have.monorepo packages instead od a single package. We will deprecate that single package. Try using '@graphql-toolkit/file-loading'.

**Comment by ahrbil** [comment]
@ardatan At first throws an error about unixify package not found after adding it everything works on windows. thanks for your fix.
However, I'm still getting the error when deploying to Zeit now but I think it is related to Zeit and not graphql-toolkit.

**Comment by ardatan** [comment]
New fix is available in `0.8.0` :) 
Maybe Zeit bundles your code instead of keeping the source code structure.

**Comment by ahrbil** [comment]
Yes exactly.
I need to tell @now/node to include the files.
Everything works now. 
Thank you @ardatan.
